### ISSUE TITLE
Cloning Stage 4 Bosses in Imperishable Night?

### ISSUE THREAD

**Issue by Escope12** [thpatch/thtk#104]
Hi. Is it possible to clone Stage 4A and Stage 4B to make a Stage 4C and Stage 4D so that when you play as Sakuya and Remilia, you battle Youmu Konpaku on Stage 4D and if you play as Youmu and Yuyuko, you battle Sakuya Izayoi on Stage 4C?

**Comment by brliron** [comment]
You've already been directed to the ZUNcode Discord server, and this Discord is a better place to answer your question than here, so I'm closing this issue.
