### ISSUE TITLE
thecl: always ' 4 bytes left over when parsing format "" '

### ISSUE THREAD

**Issue by AlyssWolf** [thpatch/thtk#11]
After compiling the newest version of thtk (for Ubuntu), I attempted to dump all of LoLK's ECL scripts but I always get the following errors when dumping st05bs.ecl and st07bs.ecl:
`thecl:value_list_from_data: 4 bytes left over when parsing format ""`

It doesn't do this on any of the other files, and an older version I got from someone else doesn't appear to have this issue either.

Example console input and output where it occurs:
`$ ./thecl d15 ../Project/BuildFiles/st05bs.ecl > test.txt
thecl:value_list_from_data: 4 bytes left over when parsing format ""
thecl:value_list_from_data: 4 bytes left over when parsing format ""
thecl:value_list_from_data: 4 bytes left over when parsing format ""
thecl:value_list_from_data: 4 bytes left over when parsing format ""
Segmentation fault (core dumped)`

**Comment by VBChunguk** [comment]
What older version did you use? Does it recompile well?

```
thecl d15 st05bs.ecl > test.txt
thecl c15 test.txt > st05bs-b.ecl
diff st05bs.ecl st05bs-b.ecl
```

**Comment by AlyssWolf** [comment]
It was the newest version, not an older version. And when this happens it leaves the script unfinished so it can't be recompiled.

**Comment by Nutzer** [comment]
This _should_ fix the issue.
(I'm sorry for jumping in like that. I hope I wasn't interfering in anyone's work here)

**Comment by AlyssWolf** [comment]
Thank you, that issue seems to be fixed, but now another one appeared, which I submitted here https://github.com/thpatch/thtk/issues/13
