### ISSUE TITLE
thanm doesn't work with full th19

### ISSUE THREAD

**Issue by zakernichny** [thpatch/thtk#110]
Release version of thanm couldn't extract any of the images from the full version of th19, returning garbage PNGs. Below is one of the "images" extracted from ascii.anm.
![ascii](https://github.com/thpatch/thtk/assets/32784787/d9dc5dc1-afbb-4b95-8e66-43cb30e03b21)
After building the latest version of thtk the issue persisted. I checked anm extraction on the trial version just in case - works fine.

**Comment by DankRank** [comment]
indeed. zun changed the format

**Comment by mikegoutokujiii** [comment]
Do I have to build the .exe myself for it to work?

**Comment by Dobby233Liu** [comment]
There's nightlies now https://nightly.link/thpatch/thtk/workflows/build/master
