### ISSUE TITLE
th19: (thanm) bubble missing

### ISSUE THREAD

**Issue by shirokurakana** [thpatch/thtk#115]
every time i repack `front.anm`, repack `th19.dat`, and then run game, both ends of dialogue bubble are missing.

**Comment by shirokurakana** [comment]
here is the screenshots.
![1.png](https://s2.loli.net/2023/08/27/KtoqMJevnLNc5Q2.png)
![2.png](https://s2.loli.net/2023/08/27/8JNhP5uOWi42wvS.png)

**Comment by 32th-System** [comment]
https://github.com/thpatch/thtk/issues/111

**Comment by DankRank** [comment]
fixed in 58be110

add a `-u` flag while extracting a file (do it for both the `-l` and the `-x` command), and you'll be able to repack it perfectly
