### ISSUE TITLE
Translate known instructions in thecl

### ISSUE THREAD

**Issue by UltimaOmega** [thpatch/thtk#12]
Would be nice if we could have thecl translate the known instructions. There seems to be several documentation sites floating around. Like [http://nutzer.bplaced.net/Database/](url) for example. At the very least, TH13 - TH15 as those seem to have the most consistent instruction sets.

This would make interpreting the ecl scripts easier if say functions like ins_601(0) was translated to fireBullet(0); or ins_301(...) to createEnemy(...);

**Comment by DankRank** [comment]
IMO if this gets implemented, the instruction mnemonics should be supplied by user instead of being built-in.

**Comment by UltimaOmega** [comment]
That's would be even better, as it would allow us to manually adjust them in the event the instructions change in future Touhou releases.
