### ISSUE TITLE
thecl missing ins_570 and ins_571 in TH15 format table

### ISSUE THREAD

**Issue by AlyssWolf** [thpatch/thtk#13]
When extracting certain ECL scripts from LoLK, ins_570() and ins_571() appear in the scripts, but when I try to compile those scripts I get the errors "thecl: id 570 was not found in the format table" and "thecl: id 571 was not found in the format table".

570 appears in st01mbs.ecl, st01mbs2.ecl, st02mbs.ecl, st03mbs.ecl, st04mbs.ecl, st06.ecl, and st07mbs.ecl.
571 appears in st02.ecl, st03.ecl, st04.ecl, st05.ecl and st07.ecl.
Neither appear to have any arguments.

I have the newest version of THTK from the latest commit.

**Comment by Nutzer** [comment]
That should be it.
