### ISSUE TITLE
Where did extracted file go?

### ISSUE THREAD

**Issue by Trung0246** [thpatch/thtk#14]
thdat.1.htm said that the extracted file will go in same folder that .dat file located, but I don't see anything...

Currently using `C:\<really long path>\thdat.exe x14 C:\<really long path>\th14.dat`, is that legal syntax?

**Comment by nmlgc** [comment]
The files are extracted to the [current *working* directory](https://github.com/thpatch/thtk/blob/master/thdat/thdat.1#L81), which may be different from the directory the .dat file is located in. (It's the directory that is displayed at your prompt, or if you enter `cd`.)
