### ISSUE TITLE
STATUS_ACCESS VIOLATION in thecl c15

### ISSUE THREAD

**Issue by Nutzer** [thpatch/thtk#2]
I have  a problem in thecl for th15:
I assume there is something wrong with the  (In the thecl documentation for th10 it's called "Stacktrace" but I don't know the correct name for it...) in c15.
Writing something like "1;", "[10000];" or "%A = 10.0f;" will cause an error.
Using c14 works.

(The Stackdumpfile:)
Exception: STATUS_ACCESS_VIOLATION at eip=0040820E
eax=00000000 ebx=00000122 ecx=800559B0 edx=00000000 esi=00000001 edi=0028B73E
ebp=0028BFE0 esp=0028B4C8 program=C:\Users\Nutzer\bin\thecl.exe, pid 8148, thread main
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
0028BFE0  0040820E (00000007, 00000002, 00000000, 00000000)

**Comment by VBChunguk** [comment]
If you can build thtk yourself, please build the commit cdca1a9 and tell me the result. I don't have the development environment now...

**Comment by VBChunguk** [comment]
I didn't check some version checking code, and this made thecl think that version 15 is invalid. This bug is fixed now.
