### ISSUE TITLE
thanm.exe can't run and keep popping up "This app can't run on your PC", Windows 10 64-bit

### ISSUE THREAD

**Issue by Trung0246** [thpatch/thtk#20]

**Comment by ManDude** [comment]
Works for me.

**Comment by DankRank** [comment]
1) does this happen with other executables? (thdat, thecl, thmsg)
2) did you compile it? or did you download the binary?
3) if you downloaded, try redownloading it
4) if you compiled:
4.a) what compiler did you use?
4.b) did you checkout the submodules? (`git submodule update --init`)

**Comment by Trung0246** [comment]
1) No
2) Downloaded it in release
3) Downloading again now

Some more information: after run it for first time with wrong command, for example:
`>C:\<redacted>\thanm.exe <wrong command here> C:\<redacted>\<somefiles>.anm`
Then the behavior as expected: the exe throw error with available commands and bug report gmail.
After that, I take a look at thanm.exe and saw "0 KB", I think the file is somehow corrupted, and when double click it, it pop ups that notification, and run in cmd it said:
`>Access is denied`
And the pop ups once again show up.
If you want to get the corrupt file, I will send it to you, and after redownloading it, it work again, so you may close this issue if you want.

**Comment by DankRank** [comment]
It looks like you somehow made thanm overwrite itself. You probably entered thanm.exe more than once in the command.
