### ISSUE TITLE
thecl does not verify instruction parameter count when compiling

### ISSUE THREAD

**Issue by jinchangdoing** [thpatch/thtk#22]
When you accidentally put more parameters into an ins than it supposed to be
you will face a dangerous  bug.
packing with more parameters wont even warn you
but you cant not unpack the ecl file until you find the exact ins with more parameters,which is almost impossible.Although you can find out the that in the txt file easily(still not that easy),the problem is
what if you packed the file with more parameters , then push the unpack button ?
your txt file will be destroyed and your ecl file will be locked, whicn means the file will be lost

**Comment by ManDude** [comment]
Reminder to add exceptions for instructions that have _ff, _fS, _Sf, or _SS in the arguments (so, the ones that called other subroutines).
