### ISSUE TITLE
thanm.exe has stopped working

### ISSUE THREAD

**Issue by PuiAnpan** [thpatch/thtk#27]
![www](https://user-images.githubusercontent.com/31733940/30165059-dc96997c-9408-11e7-9bca-6782e4ec4d6c.PNG)

**Comment by brliron** [comment]
Could you provide more details?
How does it crash? Did you just double-click on it? Did you drag a file on it? If so, which file? Did you run a command-line? If so, could you copy the command line you entered and tell us which files were involved? And which version of thanm? Is it the thtk-8 on https://github.com/thpatch/thtk/releases? Another version from this Github project? Or a version downloaded somewhere else?
