### ISSUE TITLE
thecl.exe from thtk8 corrupts ecl files from EoSD, PCB, IN (and maybe PoFV)

### ISSUE THREAD

**Issue by nyanlyar** [thpatch/thtk#31]
How to reproduce this bug:
- Take original .ecl files from th06e_ST.DAT (unpacking was done by thdat.exe from 7th release, however, unpacking archive using thdat.exe from 8th release produces identical (here and later, identical means identical according to md5) files, so I believe this is irrelevant)
- Dump them using thecl.exe from thtk8
- Create .ecl files back from this dump (using thecl.exe from thtk8)
- Create .DAT archive using newly-produced ecl files and try to run the game with this archive

Expected results:
The game runs exactly the same as it would with original .DAT archive
Results:
It doesn't. Most stages just crash after a few seconds. Stage 5 doesn't, but instead runs forever, because Sakuya is invincible, doesn't attack and doesn't have a working timer. Extra Stage displays all kinds of issues, such as: enemies not spawning, enemies spawning at wrong positions, including somewhere beyond the screen, enemies using wrong attacks, and such.

EoSD here is just an example: ecl files from PCB and IN got corrupted in the same fashion.
PoFV seems to be affected, as ecl files produced by thtk8 aren't identical to the original ones while ecl files produced by thtk7 are. However, I am unsure what those files correspond to, so I can't test it.
MoF seems to be unaffected (files produced by thtk8 thecl are identical), so I think it is unlikely later games would be affected.

This test was performed on Debian GNU/Linux 4.9.0-2-amd64 using Wine 1.8.7-2 32-bit and on Windows 7 SP1 64-bit with identical results.

If you're unable to reproduce the bug, I've attached an archive that contains corrupted .ecl files for EoSD.
It also contains files produced by thtk7. Those are not corrupted and work flawlessly.

[thtk8_issue.zip](https://github.com/thpatch/thtk/files/1430478/thtk8_issue.zip)

**Comment by DankRank** [comment]
According to @nmlgc, this is fixed in next release.

See this commit 4bdf6f46371e218307385f4fb4b836f7c3b77822

**Comment by Lymia** [comment]
I have released thtk 9 with a fix to this bug.
