### ISSUE TITLE
Compiling fails on Linux with CMake 3.9.1

### ISSUE THREAD

**Issue by thsys** [thpatch/thtk#32]
OS: Ubuntu 17.10
Architecture: x86_64 / AMD64

CMake output (explains which version numbers the required utilities have):
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test PACK_PRAGMA
-- Performing Test PACK_PRAGMA - Success
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off_t
-- Check size of off_t - done
-- Check size of size_t
-- Check size of size_t - done
-- Check size of ssize_t
-- Check size of ssize_t - done
-- Looking for libgen.h
-- Looking for libgen.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for _splitpath
-- Looking for _splitpath - not found
-- Looking for mempcpy
-- Looking for mempcpy - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for munmap
-- Looking for munmap - found
-- Looking for feof
-- Looking for feof - found
-- Looking for fileno
-- Looking for fileno - found
-- Looking for fread
-- Looking for fread - found
-- Looking for fwrite
-- Looking for fwrite - found
-- Looking for getc
-- Looking for getc - found
-- Looking for putc
-- Looking for putc - found
CMake Error at thanm/CMakeLists.txt:3 (file):
  file COPY cannot find
  "/home/thsys/Programs/Setup/thtk/thanm/zlib-ng/zconf.h.in".

CMake Error at thanm/CMakeLists.txt:5 (file):
  file RENAME failed to rename

    /home/thsys/Programs/Setup/thtk/build/thanm/zlib-ng/zconf.h.in

  to

    /home/thsys/Programs/Setup/thtk/build/thanm/zlib-ng/zconf.h

  because: No such file or directory

You have called ADD_LIBRARY for library z without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Looking for pow
-- Looking for pow - not found
-- Looking for pow
-- Looking for pow - found
CMake Error at thanm/CMakeLists.txt:30 (file):
  file COPY cannot find
  "/home/thsys/Programs/Setup/thtk/thanm/libpng/scripts/pnglibconf.h.prebuilt".

CMake Error at thanm/CMakeLists.txt:32 (file):
  file RENAME failed to rename

    /home/thsys/Programs/Setup/thtk/build/thanm/libpng/pnglibconf.h.prebuilt

  to

    /home/thsys/Programs/Setup/thtk/build/thanm/libpng/pnglibconf.h

  because: No such file or directory

CMake Warning (dev) at /usr/share/cmake-3.9/Modules/FindOpenMP.cmake:200 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "c" will no longer be dereferenced when the policy is
  set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindOpenMP.cmake:324 (_OPENMP_GET_FLAGS)
  thdat/CMakeLists.txt:3 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found BISON: /usr/bin/bison (found version "3.0.4") 
-- Found FLEX: /usr/bin/flex (found version "2.6.1") 
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Configuring incomplete, errors occurred!
See also "/home/thsys/Programs/Setup/thtk/build/CMakeFiles/CMakeOutput.log".
See also "/home/thsys/Programs/Setup/thtk/build/CMakeFiles/CMakeError.log".

CMakeOutput.log and CMakeError.log can be found here: https://goo.gl/sTqS21
(This error report would be way too long, if I copy and pasted the contents of those files)

**Comment by brliron** [comment]
From what I read in the CMakeLists.txt files, thanm needs libpng (which itself needs zlib). You have 2 choices: either use the versions installed on your computer, or have them built automatically.
- To use the version on your computer, you need to disable WITH_LIBPNG_SOURCE. I'm not really used to cmake, but I guess you can do something like `cmake WITH_LIBPNG_SOURCE=OFF` or `CMAKE WITH_LIBPNG_SOURCE=0`. If it doesn't work, just go and edit CMakeLists.txt, line 93, replace ON with OFF.
- To have cmake build them for you, just clone the repo using the --recursive switch: `git clone https://github.com/thpatch/thtk.git --recursive`, then run cmake like you did. If you don't want to re-clone the repo, you can instead run `git submodule init` then `git submodule update` in the repo you already cloned.

**Comment by thsys** [comment]
Running the command `git submodule init` and `git submodule update`, then creating and entering the build folder and running `cmake ..` `make` `sudo make install` made the build work.
When you put `git submodule init` and `git submodule update` before `mkdir build && cd build` in to the build instructions contained in the file INSTALL, I consider the problem solved. :)
