### ISSUE TITLE
[thanm] Program crashes with some TH16 files

### ISSUE THREAD

**Issue by Saigyou-R** [thpatch/thtk#33]
thanm suffers an APPCRASH when reading/extracting these files: e05.anm, st02logo.anm, st03enm.anm and title.anm.
These are the details:

  Problem Event Name:	APPCRASH
  Application Name:	thanm.exe
  Application Version:	0.0.0.0
  Application Timestamp:	59f8e7cc
  Fault Module Name:	thanm.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	59f8e7cc
  Exception Code:	c0000005
  Exception Offset:	0001bb20
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	11274
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by nmlgc** [comment]
Looks like a corrupt .dat extraction. Could you please post one of the affected .anm files here? (Zipping them will reduce their file size quite a bit.)

**Comment by Saigyou-R** [comment]
Issue resolved: I used Brightmoon to extract the files from the thXX.dat containers, instead of thdat. It seems to decode the files differently from [thdat], and some files can't be read with thanm.
Already tested with dat files from TH14, TH14.5 and TH15, all the title.anm files from these games were corrupted when extracted with Brighmoon. Thanks for your quick reply anyway.
