### ISSUE TITLE
Disabling embedded libpng fails to find system libpng

### ISSUE THREAD

**Issue by linkmauve** [thpatch/thtk#35]
When thtk is built with `-DWITH_LIBPNG_SOURCE=OFF`, thanm doesn’t include its `png_*` symbols, and this can be seen in the generated config.h which still has `#undef HAVE_LIBPNG` despite the configure script finding it correctly, and `PNG_FOUND` being `TRUE`.

**Comment by nmlgc** [comment]
Fixed, thanks for reporting!
