### ISSUE TITLE
Autodetect dat version

### ISSUE THREAD

**Issue by DankRank** [thpatch/thtk#37]
magic info:
>[2:38 PM] Egor:
>* th01-02 - 0xf388 0x9595 every 32 bytes until the end of file directory (no way to differentiate between th01/th02)
>* th03-05 - same but encrapted using the key in first 16 bytes (also can't differentiate, but the encryption keys aren't hardcoded, so it's not important)
>* th06 - PBG3
>* th07 - PBG4
>* th08/th09 - PBGZ
>* th95+ - encrapted THA1, but no way to figure out which encrypt params to use (95,10,11 / 12,125,128 / 13 / 14,143,15,16)
>* tasofro - :thonk:

>[3:32 PM] brliron:
>* Touhou 13.5 : TFPK\0
>* Touhou 14.5 / 15.5 : TFPK\1
>You can differentiate between th145 and th155 by trying different keys

---
filename heuristic should also be possible, but the first 6 games have funky shift-jis filenames, so this will be lots of fun.

**Comment by ManDude** [comment]
Should probably make this a warning when using thdat (i.e. "the arcfile has been autodetected for a different game than the one sipplied") instead of a full-on feature.

**Comment by DankRank** [comment]
I'm actually thinking of this feature being mostly an API thing. I've been trying to integrate thdat into several other projects, and the most annoying thing so far is having to ask user for version number every time :V
