### ISSUE TITLE
Gotos / Labels scince Th13

### ISSUE THREAD

**Issue by Nutzer** [thpatch/thtk#4]
Scince Th13 (well, it works in 12.5) using labels and gotos causes the game to crash / stop responding.
It seems like the offsets are not calculated correctly or the rules for jump offsets have changed.

(This is not a major Issue but it would be great to use labels in Touhou 13-15...)

**Comment by VBChunguk** [comment]
I think the bug is fixed now. Wrong parameter types were the problem. Could you test it again with your ECL scripts?

**Comment by Nutzer** [comment]
(Could you build it for me?)

**Comment by VBChunguk** [comment]
Please wait, I need to install the mingw toolchain.

**Comment by VBChunguk** [comment]
[Binaries of revision 284.8d31c40 (Google Drive)](https://drive.google.com/open?id=0B5M_iSxbZqcRZEQ1T2F4MEd2Znc)

**Comment by Nutzer** [comment]
(Yes, it works! Thank you very much!!)
