### ISSUE TITLE
What can I do with the CV1/CV2/PAT files extracted from .dat files?

### ISSUE THREAD

**Issue by strongrex2001** [thpatch/thtk#43]
I tried thdat on TH12.3, th123a.dat.
A huge amount of files are extracted.
Judging from the file names, I think the files are not corrupted.
But what can I further do with the .cv2/.cv1/.pat files?
thanm/thecl/thmsg all SEGFAULT

**Comment by brliron** [comment]
Well, thtk is mostly for ZUN games. Th105 and th123 dat files are supported, but the files in it aren't.
IIRC, cv0 files are scenario files, cv1 are CSV files, and cv2 are images. Cv0 and cv1 files are encrypted, you can decrypt them with decrypt_cv0 from here: http://brliron.tk/th105/. And for cv2 files, you can use cv2-png from here: http://brliron.tk/nsml-megamari/.
But, I remember I had the script files before writing these tools, so there must be some other tools somewhere to do the conversion. Maybe I used mauve's tools? https://en.touhouwiki.net/wiki/User:Mauve

And for pat files, I don't know any tool to edit them. I made one for th135/th145/th155 (https://github.com/brliron/135tk/tree/master/read_pat), but IIRC it doesn't work with the th123 files, and making it work would require a lot of work.

**Comment by strongrex2001** [comment]
Thank you for answering! I've found the corresponding tools at
https://github.com/kghost/th123_toolset
