### ISSUE TITLE
Project depends on bison but is not GPL

### ISSUE THREAD

**Issue by ExpHP** [thpatch/thtk#57]
I was looking through your licenses to see if this project was permissively licensed.  It looks like you did at least intend to permissively license it...

Unfortunately, one of the files you include (COPYING.bison.txt) is the full (i.e. non-lesser) GPL.  If thtk does indeed use this library, then it has been "infected" and is required to be licensed under the GPL as well unless this dependency is removed.

---

Side note:  The name "COPYING" is usually a GPL callsign.  If a project doesn't use GPL I would suggest it's better to name the file LICENSE.

**Comment by nurupo** [comment]
This is a common misconception. If you write code that has a GPL dependency, you can license your code however you want as long as its license is compatible with GPL. For example, you can license your code under the MIT license just fine. The "infection" you speak of happens when you **combine** your code with the GPL code - then the final product, usually a binary file, is treated as being GPL licensed, so the users receiving the binary can exercise all of their GPL freedoms, like requesting a copy of your source code, even though it's MIT.

**Comment by nurupo** [comment]
Now coming back from that hypothetical example to thtk. Bison is a parser generator, so I would assume that Bison's code is not present in the final binary, just the code of the generated parser by Bison, and most parser generators have very permissive terms for the generated parser code. [These are Bison's terms](https://www.gnu.org/software/bison/manual/html_node/Conditions.html), and it's also mentioned at the very bottom of [COPYING.bison.txt](https://github.com/thpatch/thtk/blob/c07c8e0996e0d21a2fa30c5c41bd7989d0927344/COPYING.bison#L678-L689). So unless thtk final binary uses Bison's code that is not just a parser generated by Bison - it should be fine and your concern is unwarranted. I'm not familiar with thtk though, so maybe someone can chime in.

**Comment by ExpHP** [comment]
> The "infection" you speak of happens when you combine your code with the GPL code - then the final product, usually a binary file, is treated as being GPL licensed, so the users receiving the binary can exercise all of their GPL freedoms, like requesting a copy of your source code, even though it's MIT.

My feeling is that it is misleading to license the project under MIT, when the terms of the GPL affects other projects that include it.  All of the code can be MIT licensed, but the project as a whole unit should be GPL.

>  Bison is a parser generator, so I would assume that Bison's code is not present in the final binary, just the code of the generated parser by Bison, and most parser generators have very permissive terms for the generated parser code.

Okay, that definitely changes things.  Sounds like the terms of the GPL *do not* extend to this work, then.

**Comment by DankRank** [comment]
GPL indeed doesn't apply here.
