### ISSUE TITLE
Some instructions that exists but cannot recognized by thtk

### ISSUE THREAD

**Issue by jinchangdoing** [thpatch/thtk#6]
I found that ins_705(int,float,float),ins_707(int,float,float),ins_709(int,float) do exist since th13
Zun  made them but didn`t use them.

and some more: parameters of ins_86 and ins_89 are all floats.

**Comment by nmlgc** [comment]
Thanks for the tip, I added the remaining laser-related functions found in the binary as well. Also, I gave you commit access to this repository, so feel free to commit these sorts of changes yourself from now on.
