### ISSUE TITLE
Couldn't build thecl successfully

### ISSUE THREAD

**Issue by cykaal** [thpatch/thtk#67]
[ 63%] [BISON][EcsParse] Building parser with bison 3.0.4
ecsparse.y:568.8-14: error: syntax error, unexpected %expect
     |  %expect 8 { yyerror(state, "deprecated syntax, use parens around expr"); } Expression  %expect 2
        ^^^^^^^
ecsparse.y:634.37-43: error: syntax error, unexpected %expect
     "unless" ParenExpression[cond]  %expect 1 {
                                     ^^^^^^^
ecsparse.y:1309.19-25: error: syntax error, unexpected %expect
     | IDENTIFIER  %expect 2 {
                   ^^^^^^^
ecsparse.y:1349.14-20: error: syntax error, unexpected %expect
     INTEGER  %expect 1 {

I have never used bison before, so I am not clear what is wrong.

**Comment by DankRank** [comment]
This feature (per-rule %expect) was introduced in bison 3.2.90 (2019-01-12), while you're running 3.0.4 (2015-01-23). I'll remove them, since they're only useful for developers, and it seems like a lot of linux distros still have old versions of bison.

**Comment by cykaal** [comment]
Thank you. I thought I was uptodate, while ubuntu1804 offical actually stays at a rather old version of bison. And the the install instruction doesn't specify the version for bison.
It works now.
