### ISSUE TITLE
Compiling fails on macOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by sclsj** [thpatch/thtk#70]
cmake version 3.16.1
GNU Make 3.81
Cmake Output: 
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test PACK_PRAGMA
-- Performing Test PACK_PRAGMA - Failed
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off_t
-- Check size of off_t - done
-- Check size of size_t
-- Check size of size_t - done
-- Check size of ssize_t
-- Check size of ssize_t - done
-- Looking for libgen.h
-- Looking for libgen.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/mman.h
-- Looking for sys/mman.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for _splitpath
-- Looking for _splitpath - not found
-- Looking for mempcpy
-- Looking for mempcpy - not found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for munmap
-- Looking for munmap - found
-- Looking for feof
-- Looking for feof - found
-- Looking for fileno
-- Looking for fileno - found
-- Looking for fread
-- Looking for fread - found
-- Looking for fwrite
-- Looking for fwrite - found
-- Looking for getc
-- Looking for getc - found
-- Looking for putc
-- Looking for putc - found
-- Looking for pow
-- Looking for pow - found
-- Found OpenMP_C: -Xclang -fopenmp (found version "3.1") 
-- Found OpenMP_CXX: -Xclang -fopenmp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
-- Found BISON: /usr/bin/bison (found version "2.3") 
-- Found FLEX: /usr/bin/flex (found version "2.5.35") 
-- Found OpenMP_C: -Xclang -fopenmp  
-- Found OpenMP_CXX: -Xclang -fopenmp  
-- Found OpenMP: TRUE   
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: /private/var/root/thtk/build

Make output: 
Scanning dependencies of target z
[  1%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/adler32.c.o
[  2%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/compress.c.o
[  3%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/crc32.c.o
[  5%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/deflate.c.o
[  6%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/deflate_fast.c.o
[  7%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/deflate_medium.c.o
[  8%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/deflate_slow.c.o
[ 10%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/functable.c.o
[ 11%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/infback.c.o
[ 12%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/inffast.c.o
[ 13%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/inflate.c.o
[ 15%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/inftrees.c.o
[ 16%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/match.c.o
[ 17%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/trees.c.o
[ 18%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/uncompr.c.o
[ 20%] Building C object extlib/CMakeFiles/z.dir/zlib-ng/zutil.c.o
[ 21%] Linking C static library libz.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libz.a(deflate_medium.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libz.a(deflate_medium.c.o) has no symbols
[ 21%] Built target z
Scanning dependencies of target png
[ 22%] Building C object extlib/CMakeFiles/png.dir/libpng/png.c.o
[ 23%] Building C object extlib/CMakeFiles/png.dir/libpng/pngerror.c.o
[ 25%] Building C object extlib/CMakeFiles/png.dir/libpng/pngget.c.o
[ 26%] Building C object extlib/CMakeFiles/png.dir/libpng/pngmem.c.o
[ 27%] Building C object extlib/CMakeFiles/png.dir/libpng/pngpread.c.o
[ 28%] Building C object extlib/CMakeFiles/png.dir/libpng/pngread.c.o
[ 30%] Building C object extlib/CMakeFiles/png.dir/libpng/pngrio.c.o
[ 31%] Building C object extlib/CMakeFiles/png.dir/libpng/pngrtran.c.o
[ 32%] Building C object extlib/CMakeFiles/png.dir/libpng/pngrutil.c.o
[ 33%] Building C object extlib/CMakeFiles/png.dir/libpng/pngset.c.o
[ 35%] Building C object extlib/CMakeFiles/png.dir/libpng/pngtrans.c.o
[ 36%] Building C object extlib/CMakeFiles/png.dir/libpng/pngwio.c.o
[ 37%] Building C object extlib/CMakeFiles/png.dir/libpng/pngwrite.c.o
[ 38%] Building C object extlib/CMakeFiles/png.dir/libpng/pngwtran.c.o
[ 40%] Building C object extlib/CMakeFiles/png.dir/libpng/pngwutil.c.o
[ 41%] Linking C static library libpng.a
[ 41%] Built target png
Scanning dependencies of target util
[ 42%] Building C object util/CMakeFiles/util.dir/file.c.o
/private/var/root/thtk/util/file.c:85:9: warning: implicit declaration of
      function 'fread_unlocked' is invalid in C99
      [-Wimplicit-function-declaration]
    if (fread_unlocked(buffer, size, 1, stream) != 1 && size != 0) {
        ^
/private/var/root/thtk/util/file.c:105:9: warning: implicit declaration of
      function 'fwrite_unlocked' is invalid in C99
      [-Wimplicit-function-declaration]
    if (fwrite_unlocked(buffer, size, 1, stream) != 1 && size != 0) {
        ^
2 warnings generated.
[ 43%] Building C object util/CMakeFiles/util.dir/list.c.o
[ 45%] Building C object util/CMakeFiles/util.dir/program.c.o
[ 46%] Building C object util/CMakeFiles/util.dir/util.c.o
[ 47%] Building C object util/CMakeFiles/util.dir/value.c.o
/private/var/root/thtk/util/value.c:204:9: warning: format specifies type
      'unsigned int *' but the argument has type 'char (*)[4]' [-Wformat]
        READ(u, value->val.C);
        ^~~~~~~~~~~~~~~~~~~~~
/private/var/root/thtk/util/value.c:160:30: note: expanded from macro 'READ'
    if (sscanf(text, "%" #f, &x) != 1) { \
                      ~~~~   ^~
1 warning generated.
[ 48%] Building C object util/CMakeFiles/util.dir/mygetopt.c.o
[ 50%] Linking C static library libutil.a
[ 50%] Built target util
Scanning dependencies of target thanm
[ 51%] Building C object thanm/CMakeFiles/thanm.dir/thanm.c.o
In file included from /private/var/root/thtk/thanm/thanm.c:37:
In file included from /private/var/root/thtk/thanm/image.h:33:
/private/var/root/thtk/extlib/thtypes/anm_types.h:8:10: warning: the current
      #pragma pack aligment value is modified in the included file
      [-Wpragma-pack]
#include "pragma_push.h"
         ^
/private/var/root/thtk/extlib/thtypes/pragma_push.h:11:9: note: previous
      '#pragma pack' directive that modifies alignment is here
#pragma pack(push, 1)
        ^
In file included from /private/var/root/thtk/thanm/thanm.c:37:
In file included from /private/var/root/thtk/thanm/image.h:33:
/private/var/root/thtk/extlib/thtypes/anm_types.h:117:10: warning: the current
      #pragma pack aligment value is modified in the included file
      [-Wpragma-pack]
#include "pragma_pop.h"
         ^
note: previous '#pragma pack' directive that modifies alignment is here
2 warnings generated.
[ 52%] Building C object thanm/CMakeFiles/thanm.dir/image.c.o
In file included from /private/var/root/thtk/thanm/image.c:37:
In file included from /private/var/root/thtk/thanm/image.h:33:
/private/var/root/thtk/extlib/thtypes/anm_types.h:8:10: warning: the current
      #pragma pack aligment value is modified in the included file
      [-Wpragma-pack]
#include "pragma_push.h"
         ^
/private/var/root/thtk/extlib/thtypes/pragma_push.h:11:9: note: previous
      '#pragma pack' directive that modifies alignment is here
#pragma pack(push, 1)
        ^
In file included from /private/var/root/thtk/thanm/image.c:37:
In file included from /private/var/root/thtk/thanm/image.h:33:
/private/var/root/thtk/extlib/thtypes/anm_types.h:117:10: warning: the current
      #pragma pack aligment value is modified in the included file
      [-Wpragma-pack]
#include "pragma_pop.h"
         ^
note: previous '#pragma pack' directive that modifies alignment is here
/private/var/root/thtk/thanm/image.c:46:10: warning: case value not in
      enumerated type 'format_t' [-Wswitch]
    case FORMAT_RGBA8888:
         ^
/private/var/root/thtk/thanm/image.h:37:25: note: expanded from macro
      'FORMAT_RGBA8888'
#define FORMAT_RGBA8888 ((format_t)-1)
                        ^
3 warnings generated.
[ 53%] Linking C executable thanm
Undefined symbols for architecture x86_64:
  "_fread_unlocked", referenced from:
      _file_read in libutil.a(file.c.o)
  "_fwrite_unlocked", referenced from:
      _file_write in libutil.a(file.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [thanm/thanm] Error 1
make[1]: *** [thanm/CMakeFiles/thanm.dir/all] Error 2
make: *** [all] Error 2

**Comment by DankRank** [comment]
this was fixed a long time ago in 1a56cb6bac550738b2c839a8fddf533998e33375 and 2977af651aaabe052f355e37733910036d8c0d73
