### ISSUE TITLE
add label support to the unpacked .anm files

### ISSUE THREAD

**Issue by RUEEE** [thpatch/thtk#71]
the corrent format of unpacked .anm files is "Instruction #xxx: a b c..."
but if an ins is added or removed , all inses are out of order(though thanm can still work)
maybe it's better to use the labels like thecl instead of using #xxx to make the codes more readable
something like this for example:
ins_300(1);
ins_400(0.0f,0.0f);
a:
10:
ins_400(0.0f,0.0f);
20:
ins_200(a,0);
ins_3();

(arg1 of ins_200 should be label
arg2 of ins_201 should be label
arg3 of ins_202 to ins_213 should be label)

**Comment by 32th-System** [comment]
Check out this branch https://github.com/thpatch/thtk/tree/thanm-new-spec-format
