### ISSUE TITLE
Why not unify the formats of unpacked ecl, description and std?

### ISSUE THREAD

**Issue by purENDKING** [thpatch/thtk#72]
As you know, the formats of the three types of files are too different.
The ecl has relative time labels and labels.The description has complicated time.The std has time labels but no labels.It's hard to write description and std.
So I hope the formats can be unified as the ecl formats.

**Comment by ManDude** [comment]
A true unification simply would not be possible due to how each project has to use its own parser (since they ARE different formats), but attempts at re-using code are still being made.
