### ISSUE TITLE
A bug of the `switch`

### ISSUE THREAD

**Issue by purENDKING** [thpatch/thtk#73]
I use a `switch`, and pack the source file. Then I unpack the *.ecl. The code has a terrible problem.
This one is what I writed:
![O$T`N495~@H(}ALLGHF{75R](https://user-images.githubusercontent.com/53564372/77223686-d53e0000-6b99-11ea-80bc-c16ec4674820.png)

This one is what it generated:
![@JY66B 7Y`CQ759CMP{6G~H](https://user-images.githubusercontent.com/53564372/77223761-5e553700-6b9a-11ea-97c4-9fd5abcc849b.png)

![9QCC$TXL3@)%AK )BJD`) T](https://user-images.githubusercontent.com/53564372/77223778-7b8a0580-6b9a-11ea-9dd9-57390c9e0e4b.png)

**Comment by Priw8** [comment]
This unfortunate bug is present in the latest release, but was fixed in cbd0f2035fc8d0262410dd4c035382ad270010fd.
