### ISSUE TITLE
Ternary operator associativity

### ISSUE THREAD

**Issue by ExpHP** [thpatch/thtk#74]
Looks like the ternary operator might have [PHP associativity](https://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/)?

```
#include "ECLinclude/ECLplus.tecl"

inline int ClipInt(int x, int a, int b) {
    return (x < a) ? a
         : (x > b) ? b
         : x;
}

printf("Clip(-1, 0, 4) = %d\n", _SS (ClipInt(-1, 0, 4))); // prints -1
printf("Clip(3, 0, 4) = %d\n", _SS (ClipInt(3, 0, 4)));   // prints 3
printf("Clip(5, 0, 4) = %d\n", _SS (ClipInt(5, 0, 4)));   // prints 5 (!!!!)
```

**Comment by DankRank** [comment]
Yes, but actually no.

The grammar is left-associative, but the code gen emits both left and right associative versions as `x < a ? a : x` due to a label name collision.

Gonna push a fix later today.
