### ISSUE TITLE
for the

### ISSUE THREAD

**Issue by jinchangdoing** [thpatch/thtk#8]

**Comment by jinchangdoing** [comment]
when we edit the ecltxt file like this
%A+%B;
 ins_45(%A);
then pack to ecl file and unpack again
it will become this form again
    %A;
    %B;
    ins_51();
    ins_45(%A);
It will be very comviconvenient if it can remain the easy form when unpack

**Comment by VBChunguk** [comment]
What version of Touhou(the number after c/d parameter) did you find that bug? Does that bug appear in all versions?

**Comment by ManDude** [comment]
I didn't even know this was how you did it. In extracted LoLK ecl files (even before I edit them), I get stuff like this:
`    %A;
    0.6981317f;
    ins_53();`

**Comment by ManDude** [comment]
bump, also occurring in UFO
