### ISSUE TITLE
Negative integer/floating constants

### ISSUE THREAD

**Issue by DankRank** [thpatch/thtk#87]
Decompiling st01bs.ecl from th18tr in raw mode produces the following line
```
ins_11("EffChargePoint2", _ff 1.5707964f, _ff -1.0471976f, _SS 8, _SS 2, _SS 6);
```
It doesn't recompile. Maybe we should make it so that the lexer recognizes negative numbers?

The workaround for this particular case is `rad(-60.f)`

**Comment by ManDude** [comment]
`Maybe we should make it so that the lexer recognizes negative numbers?` please no, this was specifically changed for a reason!

I can't look at the code right now, but I'm assuming some expression optimization pass isn't running? Or is it a syntax error?

**Comment by DankRank** [comment]
Oh i see. #69

Syntax error. In this case it's Cast_Type, but a similar problem could happen with Load_Type I think.
