### ISSUE TITLE
decompiling touhou.dat (touhou 2) "th02_open: first entry offset invalid"

### ISSUE THREAD

**Issue by jali-peno** [thpatch/thtk#88]
![image](https://user-images.githubusercontent.com/38914486/116165065-0952f100-a6c9-11eb-93da-844c9691fbe2.png)
yea i dont really know what else to say here unless theres a way to get a program log to run

if you need anything else from me to diagnose just let me know ill be waiting eagerly

**Comment by DankRank** [comment]
Sorry for late reply. thdat unpacks `東方封魔.録`, not `TOUHOU.DAT`.

TOUHOU.DAT contains the image data for"ZUN soft 東方 Project" text that appears when you start the game:
![image](https://user-images.githubusercontent.com/4050457/117905688-411e8300-b2dc-11eb-94d0-eac160c412c3.png)
You can use [BFNTCONV](https://www.shrinemaiden.org/forum/index.php?topic=20614.0) to unpack that, but I assume what you want is `東方封魔.録`.
